export const users = [
  {
    "_id": "65a7b440038ef55e40a14998",
    "index": 0,
    "guid": "d3431f7b-802d-4d78-a624-5dbd4d8cd26a",
    "isActive": true,
    "balance": "$3,899.90",
    "picture": "http://placehold.it/32x32",
    "age": 34,
    "eyeColor": "brown",
    "name": "Lucas Cooper",
    "gender": "male",
    "company": "GLUKGLUK",
    "email": "lucascooper@glukgluk.com",
    "phone": "+1 (916) 435-2922",
    "address": "288 Navy Walk, Knowlton, Connecticut, 6457",
    "about": "Nostrud qui elit consequat aliqua laboris consequat elit aliquip excepteur qui ullamco. Velit officia amet ipsum et cupidatat aliquip voluptate deserunt aute consectetur cillum ullamco mollit reprehenderit. Mollit pariatur ea deserunt fugiat in eu. Mollit ipsum cillum eu aute proident. Esse do exercitation commodo sint aliqua duis reprehenderit eu in pariatur minim exercitation commodo.\r\n",
    "registered": "2014-05-06T02:26:25 -06:00",
    "latitude": -44.660682,
    "longitude": 76.96558
  },
  {
    "_id": "65a7b440bdbdc18a106d5fcb",
    "index": 1,
    "guid": "7e8081d8-f9c2-4d94-9145-49bf28709f9b",
    "isActive": false,
    "balance": "$3,063.22",
    "picture": "http://placehold.it/32x32",
    "age": 35,
    "eyeColor": "brown",
    "name": "Jessie Barron",
    "gender": "female",
    "company": "AQUAZURE",
    "email": "jessiebarron@aquazure.com",
    "phone": "+1 (914) 510-3081",
    "address": "281 Jackson Place, Holtville, New Mexico, 1656",
    "about": "Cupidatat amet irure exercitation aliquip id nisi Lorem nostrud nulla elit aute proident. Eiusmod proident labore incididunt non dolor labore ex laborum minim adipisicing esse culpa nostrud. Qui ex eiusmod ut ullamco sit qui occaecat ad dolore amet consequat do do sit. Exercitation ea aliqua eu nostrud eiusmod dolor reprehenderit nulla aliqua nostrud. Tempor sit mollit cupidatat adipisicing mollit sunt cillum et sint mollit cupidatat ut irure commodo.\r\n",
    "registered": "2014-08-12T05:30:42 -06:00",
    "latitude": -31.434321,
    "longitude": -34.736958
  },
  {
    "_id": "65a7b4401b671825e90f2a8c",
    "index": 2,
    "guid": "aa86215b-5596-413b-ae9d-dd7cc05343ad",
    "isActive": false,
    "balance": "$3,121.16",
    "picture": "http://placehold.it/32x32",
    "age": 39,
    "eyeColor": "brown",
    "name": "Bonner Garcia",
    "gender": "male",
    "company": "EXOSPACE",
    "email": "bonnergarcia@exospace.com",
    "phone": "+1 (820) 527-3327",
    "address": "677 Cobek Court, Imperial, Virgin Islands, 4562",
    "about": "Duis do tempor cillum aliquip magna excepteur. Pariatur eiusmod velit officia consequat ex ipsum amet eiusmod ut eiusmod. Proident commodo esse magna commodo voluptate magna qui et veniam non eu non. Nulla commodo enim cillum amet tempor et. Mollit et aliquip laboris ex fugiat reprehenderit. Voluptate in et ea excepteur non mollit pariatur id. Sunt et sint sint velit dolor cillum cupidatat dolore ea dolore adipisicing.\r\n",
    "registered": "2021-12-15T09:02:23 -05:00",
    "latitude": -63.201323,
    "longitude": 7.700747
  },
  {
    "_id": "65a7b440266a2f3486a5d67c",
    "index": 3,
    "guid": "f5bd2d70-9d55-4263-9775-3108c5d54e0e",
    "isActive": false,
    "balance": "$3,311.07",
    "picture": "http://placehold.it/32x32",
    "age": 23,
    "eyeColor": "green",
    "name": "Sloan Clemons",
    "gender": "male",
    "company": "ROBOID",
    "email": "sloanclemons@roboid.com",
    "phone": "+1 (843) 544-2105",
    "address": "437 Grattan Street, Garberville, Colorado, 4170",
    "about": "Deserunt ad pariatur velit ea sint laboris ullamco ea eiusmod reprehenderit id in ex. Laborum nostrud proident ad enim minim officia sit mollit irure velit adipisicing nulla. Aliqua excepteur ipsum commodo dolore in proident nisi quis. Excepteur sunt nostrud adipisicing non veniam dolore mollit incididunt laboris incididunt sunt elit id. In eu est in ipsum ex sit adipisicing veniam duis et Lorem. Culpa labore nostrud dolor ad aliquip consequat laboris reprehenderit excepteur Lorem nisi excepteur laborum. Adipisicing nulla eiusmod sit fugiat nisi laboris Lorem.\r\n",
    "registered": "2020-01-15T12:33:29 -05:00",
    "latitude": 47.920277,
    "longitude": 179.196867
  },
  {
    "_id": "65a7b440a1df4dbca6c13300",
    "index": 4,
    "guid": "91c34314-276c-4cf1-9200-c48e93b416c6",
    "isActive": false,
    "balance": "$2,875.04",
    "picture": "http://placehold.it/32x32",
    "age": 35,
    "eyeColor": "brown",
    "name": "Rochelle Madden",
    "gender": "female",
    "company": "ZILLACOM",
    "email": "rochellemadden@zillacom.com",
    "phone": "+1 (824) 575-2610",
    "address": "274 Vandam Street, Odessa, Arizona, 9737",
    "about": "Do incididunt qui nulla minim qui nulla ad esse. Dolor nisi ea aliquip culpa fugiat duis id. Minim fugiat laborum consectetur proident. Esse deserunt exercitation proident velit. Qui sit tempor aliquip sit dolore ipsum eiusmod exercitation cupidatat eu cillum. Ad pariatur nisi laborum esse voluptate incididunt aliqua.\r\n",
    "registered": "2014-09-16T04:36:52 -06:00",
    "latitude": 8.976507,
    "longitude": 48.946762
  }
]